name: python-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps: 
      - name: install poetry
        run: |
          pip install poetry
      - name: run lint
        run: |
             make lint
      - name: run test
        run: |
            make test
             
       
