name: python-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: "Install poetry"
        run: |
          pip install poetry

      - name: "Install requirements"
        run: |
          make install

      - name: Run linter
        run: |
          make lint

      - name: Run tests
        run: |
          make test
